var __BASE = {
 lorem_ipsum: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec nisi nec enim faucibus luctus. In felis dui, iaculis id euismod eget, ultrices ut nibh. Nullam vel eros vitae turpis auctor sagittis eu at ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus dictum lacus at augue dignissim adipiscing. Vestibulum malesuada, eros sit amet sagittis ultrices, leo lacus sollicitudin tortor, ut commodo velit tellus et mi. Pellentesque facilisis nisl eget massa adipiscing id auctor massa venenatis. Duis a urna augue, sed sollicitudin lacus. Aliquam vitae arcu ut dolor tristique rutrum aliquam eu libero. Vestibulum et facilisis enim. Ut interdum blandit ornare.\
\
Donec ut nunc dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut volutpat augue sit amet ligula pretium nec consectetur sem porta. Duis varius ullamcorper ante, fermentum facilisis quam ultricies quis. Praesent convallis risus vel risus mattis hendrerit. Duis eget nunc id mi hendrerit mattis consectetur quis massa. Etiam egestas tortor nec tellus congue laoreet. Donec sodales aliquet ultricies.\
\
Proin dictum fringilla consequat. Mauris tristique, mi vitae dictum lobortis, nibh mauris dapibus dolor, et feugiat sapien erat at leo. Etiam id turpis varius nisl commodo porttitor. Aenean quam felis, malesuada aliquam pharetra pellentesque, consequat eu felis. In dapibus euismod odio, et ornare sapien mollis id. Proin dictum facilisis purus, in pretium ipsum adipiscing in. Integer et diam arcu, at hendrerit mi. Integer eu orci sed lacus aliquam faucibus sit amet non mi. Nulla facilisi. Phasellus eu mauris in nunc auctor dignissim eu nec nisi. Donec nec augue sed nibh vestibulum condimentum non quis risus. Integer hendrerit feugiat mauris sit amet elementum.\
\
Donec vestibulum dignissim neque et bibendum. Praesent varius, mauris at vulputate faucibus, lectus lorem bibendum sem, vel vulputate risus nisl ut sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean suscipit dolor at risus rhoncus sit amet porttitor eros accumsan. Etiam scelerisque lectus eget risus vulputate cursus. Praesent malesuada elementum purus, consectetur eleifend quam rhoncus eu. Maecenas pharetra tempor metus, nec laoreet eros luctus sed. Cras tellus velit, dignissim sed hendrerit in, facilisis in purus. Donec vel semper ipsum. Phasellus interdum, erat ac ullamcorper fringilla, ipsum erat vulputate libero, sed luctus orci arcu a leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer sollicitudin semper orci, et consectetur felis semper non. In hac habitasse platea dictumst. Nullam non pulvinar nisi. Praesent sit amet massa sem. Vivamus eu libero quis leo aliquam bibendum ac at magna.\
\
Fusce eget erat dolor. Vivamus elementum aliquet augue, eget tincidunt lorem tempus at. Maecenas sit amet purus lectus. In tristique scelerisque augue quis ullamcorper. Duis sit amet augue ligula. Donec interdum, dolor eget imperdiet blandit, diam neque aliquam orci, suscipit commodo ligula mauris et erat. Vestibulum cursus magna nec tellus pellentesque scelerisque mattis justo convallis. Proin ut ipsum sed augue bibendum venenatis.",
 __x: null
}
